import json
import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

PDF_DIR = Path("exports/pdfs")
PDF_DIR.mkdir(parents=True, exist_ok=True)

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; margin: 0; padding: 20px; color: #1a1a1a; font-size: 13px; }}
  .header {{ background: #1B3A6B; color: white; padding: 16px 20px; margin-bottom: 20px; }}
  .header h1 {{ margin: 0; font-size: 22px; }}
  .header .subtitle {{ font-size: 12px; opacity: 0.85; margin-top: 4px; }}
  .badge {{ display: inline-block; padding: 8px 20px; border-radius: 4px; font-size: 18px; font-weight: bold; color: white; margin: 12px 0; }}
  .RED {{ background: #C0392B; }}
  .YELLOW {{ background: #E67E22; }}
  .GREEN {{ background: #2D6A2D; }}
  .section {{ margin-bottom: 16px; }}
  .section-title {{ font-size: 13px; font-weight: bold; color: #1B3A6B; border-bottom: 1px solid #ddd; padding-bottom: 4px; margin-bottom: 8px; text-transform: uppercase; }}
  .info-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }}
  .info-item {{ font-size: 12px; }}
  .info-label {{ color: #666; font-size: 11px; }}
  .condition-item {{ padding: 6px 0; border-bottom: 1px solid #eee; font-size: 12px; }}
  .condition-rank {{ font-weight: bold; color: #1B3A6B; }}
  .soap-row {{ margin-bottom: 8px; font-size: 12px; }}
  .soap-label {{ font-weight: bold; color: #1B3A6B; }}
  .disclaimer {{ background: #FFF3CD; border: 1px solid #F5C518; padding: 10px; font-size: 11px; color: #856404; margin: 16px 0; }}
  .footer {{ margin-top: 24px; border-top: 1px solid #ddd; padding-top: 10px; font-size: 10px; color: #888; text-align: center; }}
</style>
</head>
<body>
<div class="header">
  <h1>GEMMA — Handoff Summary</h1>
  <div class="subtitle">Guided Emergency & Medical Management Assistant | Barangay Platero Health Center, City of Biñan</div>
</div>

<div class="section">
  <div class="section-title">Impormasyon ng Pasyente</div>
  <div class="info-grid">
    <div class="info-item"><div class="info-label">Pangalan</div>{name}</div>
    <div class="info-item"><div class="info-label">Edad / Kasarian</div>{age_sex}</div>
    <div class="info-item"><div class="info-label">Petsa at Oras</div>{timestamp}</div>
    <div class="info-item"><div class="info-label">BHW</div>{bhw_name}</div>
  </div>
</div>

<div class="section">
  <div class="section-title">Chief Complaint</div>
  <p style="margin:0;">{chief_complaint}</p>
</div>

<div class="section">
  <div class="section-title">Triage Level</div>
  <div class="badge {triage_level}">{triage_level}</div>
  <p style="margin:4px 0; font-size:12px;">{triage_reason}</p>
</div>

<div class="section">
  <div class="section-title">Top 5 Posibleng Kondisyon</div>
  {conditions_html}
</div>

<div class="section">
  <div class="section-title">SOAP Summary</div>
  <div class="soap-row"><span class="soap-label">S — Subjective: </span>{soap_s}</div>
  <div class="soap-row"><span class="soap-label">O — Objective: </span>{soap_o}</div>
  <div class="soap-row"><span class="soap-label">A — Assessment: </span>{soap_a}</div>
  <div class="soap-row"><span class="soap-label">P — Plan: </span>{soap_p}</div>
</div>

{image_section}

<div class="disclaimer">
  ⚠️ {disclaimer}<br>
  Hindi ito opisyal na medikal na rekord. Para sa gabay ng doktor lamang.
</div>

<div class="footer">
  Generated by GEMMA — Guided Emergency & Medical Management Assistant<br>
  Barangay Platero, City of Biñan | {generated_at}
</div>
</body>
</html>"""


def _build_html(patient: dict, bhw_name: str) -> str:
    name = patient.get("name") or "Hindi ibinigay"
    age = patient.get("age")
    sex = patient.get("sex")
    age_sex = f"{age or '—'} taon / {sex or '—'}"

    timestamp = patient.get("timestamp", datetime.utcnow())
    if isinstance(timestamp, str):
        ts_str = timestamp
    else:
        ts_str = timestamp.strftime("%Y-%m-%d %H:%M")

    top_conditions = patient.get("top_conditions", [])
    if isinstance(top_conditions, str):
        top_conditions = json.loads(top_conditions)

    conditions_html = ""
    for c in top_conditions:
        conditions_html += (
            f'<div class="condition-item">'
            f'<span class="condition-rank">#{c["rank"]}</span> '
            f'{c["condition"]} — <em>{c["plain_explanation"]}</em>'
            f'</div>'
        )

    handoff = patient.get("handoff_summary", "{}")
    if isinstance(handoff, str):
        try:
            soap = json.loads(handoff)
        except Exception:
            soap = {"S": handoff, "O": "—", "A": "—", "P": "—"}
    else:
        soap = handoff

    image_findings = patient.get("image_findings")
    image_section = ""
    if image_findings:
        image_section = f"""<div class="section">
  <div class="section-title">Nakita sa Larawan</div>
  <p style="margin:0; font-size:12px;">{image_findings}</p>
</div>"""

    return HTML_TEMPLATE.format(
        name=name,
        age_sex=age_sex,
        timestamp=ts_str,
        bhw_name=bhw_name,
        chief_complaint=patient.get("chief_complaint", ""),
        triage_level=patient.get("triage_level", "YELLOW"),
        triage_reason=patient.get("triage_reason", ""),
        conditions_html=conditions_html,
        soap_s=soap.get("S", ""),
        soap_o=soap.get("O", ""),
        soap_a=soap.get("A", ""),
        soap_p=soap.get("P", ""),
        image_section=image_section,
        disclaimer=patient.get("disclaimer", "Para sa kaalaman ng BHW lamang. Hindi ito pagsusuri ng doktor."),
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    )


def generate_pdf(patient: dict, bhw_name: str) -> str:
    patient_id = patient.get("id", "unknown")
    ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    pdf_path = PDF_DIR / f"patient_{patient_id}_{ts}.pdf"

    html_content = _build_html(patient, bhw_name)

    try:
        from weasyprint import HTML
        HTML(string=html_content).write_pdf(str(pdf_path))
        logger.info(f"PDF generated via WeasyPrint: {pdf_path}")
    except ImportError:
        _generate_with_reportlab(patient, bhw_name, str(pdf_path))
        logger.info(f"PDF generated via ReportLab: {pdf_path}")

    return str(pdf_path)


def _generate_with_reportlab(patient: dict, bhw_name: str, pdf_path: str) -> None:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.units import cm

    doc = SimpleDocTemplate(pdf_path, pagesize=A4, topMargin=1.5*cm, bottomMargin=1.5*cm)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle("title", parent=styles["Heading1"], textColor=colors.HexColor("#1B3A6B"), fontSize=18)
    sub_style = ParagraphStyle("sub", parent=styles["Normal"], textColor=colors.HexColor("#666666"), fontSize=10)
    section_style = ParagraphStyle("section", parent=styles["Heading2"], textColor=colors.HexColor("#1B3A6B"), fontSize=12)
    body_style = ParagraphStyle("body", parent=styles["Normal"], fontSize=11)
    disclaimer_style = ParagraphStyle("disclaimer", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#856404"))

    story.append(Paragraph("GEMMA — Handoff Summary", title_style))
    story.append(Paragraph("Guided Emergency & Medical Management Assistant | Barangay Platero, City of Biñan", sub_style))
    story.append(Spacer(1, 0.4*cm))

    triage_level = patient.get("triage_level", "YELLOW")
    triage_colors = {"RED": "#C0392B", "YELLOW": "#E67E22", "GREEN": "#2D6A2D"}
    badge_color = colors.HexColor(triage_colors.get(triage_level, "#E67E22"))

    badge_table = Table([[f"  {triage_level}  "]], colWidths=[5*cm])
    badge_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), badge_color),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 16),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [badge_color]),
    ]))
    story.append(badge_table)
    story.append(Spacer(1, 0.4*cm))

    story.append(Paragraph("Chief Complaint", section_style))
    story.append(Paragraph(patient.get("chief_complaint", ""), body_style))
    story.append(Spacer(1, 0.3*cm))

    handoff = patient.get("handoff_summary", "{}")
    if isinstance(handoff, str):
        try:
            soap = json.loads(handoff)
        except Exception:
            soap = {"S": handoff, "O": "—", "A": "—", "P": "—"}
    else:
        soap = handoff

    story.append(Paragraph("SOAP Summary", section_style))
    for key, label in [("S", "Subjective"), ("O", "Objective"), ("A", "Assessment"), ("P", "Plan")]:
        story.append(Paragraph(f"<b>{key} — {label}:</b> {soap.get(key, '')}", body_style))
    story.append(Spacer(1, 0.3*cm))

    story.append(Paragraph(
        "⚠️ Para sa kaalaman ng BHW lamang. Hindi ito pagsusuri ng doktor. "
        "Hindi ito opisyal na medikal na rekord.",
        disclaimer_style
    ))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph(
        f"Generated by GEMMA — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        sub_style
    ))

    doc.build(story)
